name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
