name: prebuild

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npx prebuild -t 9.4.0 -t 10.2.0 -t 11.1.1 -r electron --arch x64 -u ${{ secrets.GITHUB_TOKEN }}
      env:
        SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk
